### ISSUE TITLE
npm install 1 high severity vulnerablity

### ISSUE THREAD

**Issue by albright888** [IronCoreLabs/getting-started#17]
just noting that npm install is currently reporting 1 high severity vulnerability:

                                                                                
                       === npm audit security report ===                        
                                                                                
 Run  npm install --save-dev webpack-dev-server@3.1.10  to resolve 1 vulnerability
┌───────────────┬──────────────────────┐
│ High          │ Missing Origin Validation                                    │
├───────────────┼──────────────────────┤
│ Package       │ webpack-dev-server                                        │
├───────────────┼──────────────────────┤
│ Dependency of │ webpack-dev-server [dev]                        │
├───────────────┼──────────────────────┤
│ Path          │ webpack-dev-server                                           │
├───────────────┼──────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/725                       │
└───────────────┴──────────────────────┘

**Comment by ernieturner** [comment]
Resolved via #18, thanks!
